Hw1
cyberpanncake/Torzhkova-Tinkoff-JavaBackendCourse-Spring pull request #1
Opened 2024-02-18 20:56 UTC by cyberpanncake

Доп. задание (создание меню команд в боте) реализовано в методе Controller.addCommandMenu()

2024-02-21 20:15 UTC, strelchm requested changes

2024-02-21 20:15 UTC, strelchm commented on bot/src/main/java/edu/java/bot/controller/Controller.java
> +        bot = new TelegramBot(config.telegramToken());
Здесь мы создаем TelegramBot в конструкторе и минус этого - мы завязаны на объекте (конкретной реализации) бота. В Spring компоненты строятся на идеологии inversion of control -  контекст бинов управляет нашими бинами (pojo-объектами), см [пример ](https://www.baeldung.com/inversion-control-and-dependency-injection-in-spring#what-is-dependency-injection). Предлагаю создание бота перенести в класс конфигурации:
```
@Configuration
public class TelegramBotConfig {
    @Bean
    public TelegramBot telegramBot(ApplicationConfig config) {
        TelegramBot telegramBot = new TelegramBot(config.telegramToken());
        addCommandMenu(telegramBot);
        return telegramBot;
    }


    private void addCommandMenu(TelegramBot bot) {
        BotCommand[] commands = Arrays.stream(Command.values())
            .map(c -> new BotCommand(c.getName(), c.getDescription()))
            .toArray(BotCommand[]::new);
        bot.execute(new SetMyCommands(commands));
    }
}
```
и инжектить уже бин через конструктор. А вот в конструкторе контроллера можно сделать setUpdatesListener (либо не в конструкторе, а в @PostConstruct-методе). Тогда наша привязка к версии будет меньше и конфигурировать бота будем в отдельном месте

2024-02-21 20:15 UTC, strelchm commented on bot/src/main/java/edu/java/bot/command/Command.java
> +    private static ScrapperService service = new ScrapperService();
Не по spring-овому - жесткая завязка на реализации **ScrapperService**. Лучше инжектить бин **ScrapperService** в конкретный бин комманды

2024-02-21 20:15 UTC, strelchm commented on bot/src/main/java/edu/java/bot/command/Command.java
> +    private static String untrack(Long userId, String[] params)
При масштабировании количество команд будет расти, методы будут добавляться и файл разрастется

2024-02-21 20:15 UTC, strelchm commented on bot/src/main/java/edu/java/bot/command/Command.java
> +    START("зарегистрировать пользователя", Command::start),
Энум с методами-стратегиями хорош когда содержутся некоторые небольшие действия в "командах"
При дальнейшей логике у нас могут возникнуть проблемы, когда нужно будет в наших командах (сейчас статических методах) использовать все больше и больше классов, при инжекте в отдельные бины команд больших проблем не будет (сейчас - будем через new новые классы добавлять, вроде ScrapperService)
Предлагаю:
1. Вынести все команды в отдельные бины @Component и имплементить их от общего интерфейса команды
2. Данный энум переименовать в CommandType. Он будет возвращаться по методу в бине команды
3. Каждая команда будет выполнять действие (сейчас в функции action)
4. Коллекцию бинов мы можем заинжектить в BotConfig - где нам нужен список команд
5. В Controller мы можем заинжектить коллекцию команд и например по типу команды найти нужную и обработать. Либо можно сделать цепочку команд - будет инжектиться одна команда, которая если обработать не может, то делегирует работу следующей (наверное первый подход будет легче сделать)

2024-03-02 15:10 UTC, cyberpanncake commented
Переделала структуру классов, связанных с командами бота согласно Вашим замечаниям. Теперь команды реализуют общий интерфейс Command, помечены аннотациями Component, и список команд инжектится там, где он требуется

2024-03-02 19:04 UTC, strelchm commented on bot/src/test/java/edu/java/bot/BotApplicationTest.java
> +@SpringBootTest(classes = {BotApplication.class})
Здесь в тесте инжектится только TelegramBotConfig. Можно убрать @SpringBootTest и аргумент из конструтора, а объект конфига вручную задать - это даст прирост в перфомансе, т к контекст в тесте не будет подниматься + будет все в юнит/мок тестировании

2024-03-02 19:04 UTC, strelchm approved these changes

2024-03-02 19:41 UTC, cyberpanncake commented on bot/src/test/java/edu/java/bot/BotApplicationTest.java
> +@SpringBootTest(classes = {BotApplication.class})
Идею про производительность поняла, но помимо TelegramBotConfig SpringBoot также подтягивает и бины команд. И соответственно тогда придётся их руками тоже создавать. А если в приложении список команд будет меняться, то в тесте надо будет это актуализировать опять вручную. А ещё я пробовала сейчас убрать @SpringBootTest и задать всё вручную, но почему-то падают все тесты, updateMock не инициализируется (null). Так что пожалуй оставлю тесты как есть)

2024-03-02 19:54 UTC, strelchm commented on bot/src/test/java/edu/java/bot/BotApplicationTest.java
> +@SpringBootTest(classes = {BotApplication.class})
понял, не заметил

2024-03-03 13:12 UTC, merged