hw5
cyberpanncake/Torzhkova-Tinkoff-JavaBackendCourse-Spring pull request #6
Opened 2024-03-17 20:29 UTC by cyberpanncake

2024-03-17 21:16 UTC, cyberpanncake commented
Задания 1 и 2 реализовала, 3 и 4 постараюсь сделать в ближайшие день-два

2024-03-24 19:27 UTC, cyberpanncake commented
Доделала задания 3 и 4 (получение обновлений и отправка боту)

2024-03-28 06:42 UTC, strelchm requested changes

2024-03-28 06:42 UTC, strelchm commented on bot/src/main/java/edu/java/bot/telegram/command/components/TrackCommand.java
> +        config.linkParser().parse(link);
Так использовать бины конфигурации - плохая практика. Необходимо их самих инжетить, конфигурацию не инжектим:
`public TrackCommand(ScrapperService service, LinkParser linkParser) {
`

2024-03-28 06:42 UTC, strelchm commented on scrapper/src/main/java/edu/java/scrapper/api/service/jdbc/JdbcLinkService.java
> +    public Link remove(long tgId, URI url) throws LinkNotFoundException, ChatNotFoundException {
Здесь у нас группа операций на обновление, но транзакции нет. Необходимо поставить @Transactional над методом, что бы метод был атомарным. Там где присутсвует выборка обновления либо более одной выборки в БД необходимо делать транзакцию. В противном случае будет несколько транзакций на уровне БД

2024-03-28 06:42 UTC, strelchm commented on scrapper/src/main/java/edu/java/scrapper/api/service/jdbc/JdbcLinkService.java
> +    public Link remove(long tgId, URI url) throws LinkNotFoundException, ChatNotFoundException {
Но надо следить, что бы не было обращения к другим сервисам в транзе, т к длительные блокирующие операции в транзе - это зло

2024-04-04 21:16 UTC, cyberpanncake commented on bot/src/main/java/edu/java/bot/telegram/command/components/TrackCommand.java
> +        config.linkParser().parse(link);
Исправила на бины. Подскажите, пожалуйста, а почему это плохая практика?

2024-04-04 21:24 UTC, cyberpanncake commented on scrapper/src/main/java/edu/java/scrapper/api/service/jdbc/JdbcLinkService.java
> +    public Link remove(long tgId, URI url) throws LinkNotFoundException, ChatNotFoundException {
Добавила @Transactional к сервисам jdbc. Внутри сервиса обращений к другим сервисам нет, только к репозиториям.

2024-04-07 10:57 UTC, cyberpanncake commented
Хотела сделать merge hw5, чтобы решить все конфликты и git actions снова стал работать, но побоялась, что тогда PR закроется.

2024-04-14 00:44 UTC, merged

2024-04-20 12:14 UTC, strelchm commented on bot/src/main/java/edu/java/bot/telegram/command/components/TrackCommand.java
> +        config.linkParser().parse(link);
Например - это чревато циклическими зависимостями. При отдельных бинах вы вытаскиваете отдельный бин из контекста, а когда конфиг инжектите - то вероятность циклической зависимости (т е падения при старте приложения) увеличивается. Ну и просто инжектить конфиги - плохая практика, они как обертки для создания методов-@Bean. Вот [пример](https://github.com/kagkarlsson/db-scheduler/issues/479) возможных проблем с циклическими зависимостями, которые связаны с @Configuration

2024-04-20 12:36 UTC, cyberpanncake commented on bot/src/main/java/edu/java/bot/telegram/command/components/TrackCommand.java
> +        config.linkParser().parse(link);
Большое спасибо за объяснение! Теперь стало понятно, запомню и так делать больше не буду)