hw6
cyberpanncake/Torzhkova-Tinkoff-JavaBackendCourse-Spring pull request #8
Opened 2024-03-24 20:50 UTC by cyberpanncake

2024-04-07 06:37 UTC, strelchm requested changes

2024-04-07 06:37 UTC, strelchm commented on scrapper/src/main/java/edu/java/scrapper/api/service/jpa/JpaChatService.java
> +        Optional<Chat> ch = chatRepo.findByTgId(tgId);
```
        Chat chat = chatRepo.findByTgId(tgId).orElseThrow(ChatNotFoundException::new);
        Set<Link> links = chat.getLinks();
```

2024-04-07 08:10 UTC, cyberpanncake commented on scrapper/src/main/java/edu/java/scrapper/api/service/jpa/JpaChatService.java
> +        Optional<Chat> ch = chatRepo.findByTgId(tgId);
Спасибо за совет, так гораздо лаконичнее выглядит!

2024-04-25 05:51 UTC, strelchm approved these changes

2024-04-25 12:34 UTC, merged